name: PyNFe CI
on: [pull_request, push]
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install Flake8-pyproject
          pip install -r requirements.txt
          pip install flake8 pytest
      - name: Lint
        run: flake8 . --count --show-source --statistics
      - name: Tests
        run: pytest -v
